import { WithContext, Organization } from "schema-dts";

import { BASE_URL } from "../constants";

export const jsonLd: WithContext<Organization> = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Property Kraft",
  url: BASE_URL,
  logo: `${BASE_URL}/logo-icon.png`,
  description:
    "Property Kraft delivers trusted, end-to-end property and facility management for residential and commercial properties. Our tailored solutions maximize value, ensure seamless service, and provide full operational transparency. Experience Africa's benchmark for excellence in property management.",
  image: `${BASE_URL}/og-image.png`,
  address: {
    "@type": "PostalAddress",
    streetAddress: "Todo: update address",
    addressLocality: "Lagos",
    addressRegion: "LA",
    postalCode: "100001",
    addressCountry: "NG",
  },
  telephone: "+234 816 549 0072",
  email: "info@propertykraft.com",
  areaServed: "Africa",
  contactPoint: {
    "@type": "ContactPoint",
    telephone: "+234 816 549 0072",
    contactType: "customer service",
    email: "support@propertykraft.com",
  },
  keywords: [
    "Property Kraft",
    "Property Craft",
    "PropertyCraft",
    "property management",
    "facility management",
    "residential",
    "commercial",
    "cleaning services",
    "security services",
    "maintenance",
    "landscaping",
    "waste management",
    "Africa",
    "operational transparency",
    "end-to-end solutions",
    "client satisfaction",
    "real estate",
    "property solutions",
    "professional management",
    "24/7 support",
    "value maximization",
    "seamless service",
    "trusted management",
    "property oversight",
    "facility services",
    "property care",
    "property maintenance",
    "property security",
    "property cleaning",
    "property support",
    "property excellence",
    "properties",
  ],
};
