import { WithContext, Organization } from "schema-dts";

import { BASE_URL } from "../constants";

export const jsonLd: WithContext<Organization> = {
  "@context": "https://schema.org",
  "@type": "Organization",
  name: "Property Kraft Africa",
  url: BASE_URL,
  logo: `${BASE_URL}/logo-icon.png`,
  description:
    "Property Kraft delivers trusted, end-to-end property and facility management for residential and commercial properties. Our tailored solutions maximize value, ensure seamless service, and provide full operational transparency. Experience Africa's benchmark for excellence in property management.",
  image: `${BASE_URL}/og-image.png`,
  address: {
    "@type": "PostalAddress",
    streetAddress: "17, Ayinde Akinmade Street, Lekki Phase 1",
    addressLocality: "Lekki",
    addressRegion: "Lagos State",
    postalCode: "105102",
    addressCountry: "NG",
  },
  telephone: "+234 816 549 0072",
  email: "hello@propertykraft.africa",
  areaServed: "Lagos",
  contactPoint: [
    {
      "@type": "ContactPoint",
      telephone: "+234 816 549 0072",
      contactType: "customer service",
      email: "hello@propertykraft.africa",
      availableLanguage: "English",
      hoursAvailable: {
        "@type": "OpeningHoursSpecification",
        dayOfWeek: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
        opens: "09:00",
        closes: "18:00",
      },
    },
  ],
  foundingDate: "2020",
  numberOfEmployees: {
    "@type": "QuantitativeValue",
    value: 10,
  },
  serviceArea: {
    "@type": "GeoCircle",
    geoMidpoint: {
      "@type": "GeoCoordinates",
      latitude: 6.5244,
      longitude: 3.3792,
    },
    geoRadius: "100000",
  },
  keywords: [
    "Property Kraft Africa",
    "Property Kraft",
    "Property Craft Africa",
    "PropertyCraft",
    "property management",
    "facility management",
    "residential",
    "commercial",
    "cleaning services",
    "security services",
    "maintenance",
    "landscaping",
    "waste management",
    "Africa",
    "operational transparency",
    "end-to-end solutions",
    "client satisfaction",
    "real estate",
    "property solutions",
    "professional management",
    "24/7 support",
    "value maximization",
    "seamless service",
    "trusted management",
    "property oversight",
    "facility services",
    "property care",
    "property maintenance",
    "property security",
    "property cleaning",
    "property support",
    "property excellence",
    "properties",
    "Lagos",
    "Lekki",
    "Victoria Island",
    "Ikoyi",
    "property management Lagos",
    "facility management Nigeria",
    "property management Lekki",
    "facility management Victoria Island",
    "residential property management services Lagos",
  ],
};
